/**************
 * ADJECTIVES *
 **************/

// "general" adjectives
/* trend towards spooky, abandoned */
    "Ancient",
    "Ruined",
    "Abandoned",
    "Whispering",
    "Silent",
    "Forgotten",
    "Mysterious",
    "Collapsed",
    "Broken",
    "Remote",
    "Uncanny",
    "Murky",
    "Steaming",
    "Glowing",
    "Cold",
    "Misty",
    "Mossy",
    "Chilly",
    "Yellow",
    "Tepid",
    "Gray",
    "Forlorn",
    "First",
    "Last",
    "Imposing",
    "Wilding",
    "Bewitched",
    "Arcane",
    "Unholy",
    "Severed",
    "Dirty",
    "Wicked",
    "Ethereal",

// "nice" adjectives
/* for fountains, but maybe other things too */
    "Serene",
    "Holy",
    "Quiet",
    "Tranquil",
    "Blue",
    "Green",
    "Glittering",
    "Fresh",
    "Radiant",
    "Gleaming",
    "Prophetic",
    "Decorated",
    "Wonderful",
    "Powerful",
    "Painted",

// "neutral" adjectives
/* natural places, forest, fountains, etc   */
    "Damp",
    "Dusty",
    "Feral",
    "Fungus-covered"
    "Infinite",
    "Laughing",
    "Majestic",
    "Misty",
    "Mossy",
    "Narrow",
    "Noisome",
    "Puckish",
    "Slimy",
    "Sulphurous",
    "Verdant",
    "Viny",
    "Windy",

// "evil" adjectives
/* for names in gehennom, cursed weapons, etc */
    "Awful",
    "Blasted",
    "Blood-soaked",
    "Chaotic",
    "Discordant",
    "Doomed",
    "Evil",
    "Flea-bitten",
    "Hopeless",
    "Howling",
    "Hungry",
    "Maddening",
    "Molochian",
    "Red",
    "Scoured",
    "Shattered",
    "Shrieking",
    "Terrible",
    "Torn",
    "Vile",
    "Weeping",

/*********
 * NAMES *
 *********/

// fountain names
    "Font",
    "Pool",
    "Haven",
    "Oasis",
    "Respite",
    "Rest",
    "Tears",
    "Spring",

// forge names
    "Foundry",
    "Smithy",
    "Hammer",
    "Metalworks",
    "Forge",
    "Furnace",
    "Workshop",

// generic dungeon level names
/* these "common" names are duplicated on purpose */
    "Caves",
    "Tunnels",
    "Paths",
    "Passages",
/* the normal list is as follows: */
    "Alley",
    "Burrow",
    "Cairn",
    "Causeway",
    "Cave",
    "Chapel",
    "Court",
    "Den",
    "Folly",
    "Hideout",
    "Hovels",
    "Lookout",
    "Pass",
    "Passage",
    "Path",
    "Peak",
    "Place",
    "Point",
    "Reliquary",
    "Road",
    "Run",
    "Sorrow",
    "Table",
    "Temple",
    "Town",
    "Tunnel",
    "Way",

// bigroom names
    "Amphitheater",
    "Antechamber",
    "Arena",
    "Battleground",
    "Bazaar",
    "Canyon",
    "Cathedral",
    "Cell",
    "Chamber",
    "Gauntlet",
    "Gorge",
    "Hall",
    "Hoard",
    "Hollow",
    "Lair",
    "Manor",
    "Ravine",
    "Treasury",
    "Valley",
    "Vault",
    "Vista",

// ownernames
/* These are entities who can stand with or without a preceding "The "
 *
 * Don't use proper nouns.
 */
    "Academy",
    "Adventurer",
    "Ancient",
    "Angel",
    "Baker",
    "Beast",
    "Butcher",
    "Captain",
    "Cat",
    "Council",
    "Coward",
    "Cruel King",
    "Crusher",
    "Delver",
    "Demon",
    "Devourer",
    "Dragon",
    "Elemental",
    "Endless",
    "Explorer",
    "Faerie",
    "Giant",
    "Ghost",
    "Ghoul",
    "Goat",
    "Goblin",
    "Guardian",
    "Hero",
    "Hob",
    "Horde",
    "Hydra",
    "Imp",
    "Leocrotta",
    "Liar",
    "Lich",
    "Lost Child",
    "Lover",
    "Old Queen",
    "Penitent",
    "Pilgrim",
    "Rider",
    "Seeker",
    "Serpent",
    "Singer",
    "Sinner",
    "Soothsayer",
    "Spider",
    "Spirit",
    "Tailor",
    "Tarantula",
    "Thief",
    "Traveller",
    "Villain",
    "Viper",
    "Wererat",
    "Whisperer",
    "Wise Ruler",
    "Witch",
    "Yendorian",

// proper-noun names
/* beings   */
    "Arioch",
    "Elbereth",
    "Marduk",
    "Moloch",
/* gods     */
    "Amaterasu Omikami",
    "Anhur",
    "Anshar",
    "Anu",
    "Athena",
    "Blind Io",
    "Brigit",
    "Camaxtli",
    "Chih Sung-tzu",
    "Crom",
    "Hermes",
    "Huan Ti",
    "Huhetotl",
    "Ishtar",
    "Issek",
    "Kos",
    "Loki",
    "Lugh",
    "Manannan Mac Lir",
    "Mars",
    "Mercury",
    "Mitra",
    "Mog",
    "Odin",
    "Offler",
    "Poseidon",
    "Ptah",
    "Quetzalcoatl",
    "Raijin",
    "Set",
    "Shan Lai Ching",
    "Susanowo",
    "The Lady",
    "Thoth",
    "Tyr",
    "Venus",
/* leaders  */
    "Arthur",
    "Carnarvon",
    "Hippocrates",
    "Karnov",
    "Neferet",
    "Orion",
    "Pelias",
    "Sato",
    "The Arch Priest",
    "The Grand Master",
    "The Master of Thieves",
    "The Norn",
    "Twoflower",
/* misc     */
    "Creosote",
    "Izchak Miller",
    "The Oracle",
    "The Wizard of Yendor",
    "Vladimir",

/*********
 * NOUNS *
 *********/

// beverage
    "beer",
    "black tea",
    "blended vegetables",
    "blood wine",
    "caustic gas",
    "coffee",
    "darjeeling",
    "dark rum",
    "drool",
    "Ent-draught",
    "espresso",
    "fruit juice",
    "grappa",
    "green tea",
    "grog",
    "iridescent tea",
    "Kanar",
    "liquid courage",
    "liquid smoke",
    "moonshine",
    "napalm",
    "olive oil",
    "oolong",
    "pickle juice",
    "pirate rum",
    "poorly-distilled fuel",
    "protein shake",
    "saline solution",
    "scotch",
    "spiced rum",
    "suds",
    "synovial fluid",
    "tequila",
    "the hard stuff",
    "water",
    "wheatgrass nonsense",
    "whiskey",
    "white tea",

// beverage container
    "barrel",
    "bucket",
    "cup",
    "droplet",
    "esky",
    "flask",
    "glass",
    "handle",
    "mug",
    "pint",
    "potion",
    "saucer",
    "schooner",
    "shot",
    "tall glass",
    "tumbler",
    "vial",

/*********
 * VERBS *
 *********/

// throw (object)
    "chucks",
    "flings",
    "hurls",
    "passes",
    "throws",
    "tosses",

// hit (creature)
/* as in "the foo hits bar!" */
    "damages",
    "drubs",
    "hits",
    "strikes",
    "wounds",
